.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"  C23 port copyright 2026 Jesper Olsen (https://github.com/jesper-olsen)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "June 2026"
.SH NAME
sl \- cure your bad habit of mistyping
.SH SYNOPSIS
.B sl
[
.B \-aFcl1hV
]
.SH DESCRIPTION
.B sl
is a highly advanced animation program for curing your bad habit of mistyping.
.PP
.TP
.B \-a, \-\-accident
An accident is occurring. People cry for help.
.TP
.B \-F, \-\-fly
It flies like the galaxy express 999.
.TP
.B \-c, \-\-c51
Model C51.
.TP
.B \-l, \-\-logo
Model SL Logo.
.TP
.B \-1, \-\-one
Start at screen bottom.
.TP
.B \-h, \-\-help
Print help information.
.TP
.B \-V, \-\-version
Print version information.
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
.B Original C implementation:
Toyoda Masashi (mtoyoda@acm.org)
.PP
.B C23 port:
Jesper Olsen (https://github.com/jesper-olsen/sl)
